module.exports = {

    mockCuratedTrips: [
        {
            _id: "test01",
            trip_name: "Rocky Mountains",
            optimized_route: [],
            estimated_travel_distance: 19875030,
            estimated_travel_duration: 923847,
            image_url: "http://www.lonelyplanet.com/travel-blog/tip-article/wordpress_uploads/2013/03/GettyImages-478080583_full_cs.jpg",
            vote_count: 0,
            save_count: 0,
            comments: [],
            created: "2017-01-17",
            updated: "2017-01-17",
        },
        {
            _id: "test02",
            trip_name: "Hitoric Route 66",
            optimized_route: [],
            estimated_travel_distance: 19875030,
            estimated_travel_duration: 198387,
            image_url: "http://www.theamericanroadtripcompany.co.uk/wp-content/uploads/Mojave-Desert-Route-66-Road-Trip-Holiday-SS.jpg",
            vote_count: 0,
            save_count: 0,
            comments: [],
            created: "2017-01-17",
            updated: "2017-01-17",
        },
        {
            _id: "test03",
            trip_name: "Winding Roads",
            optimized_route: [],
            estimated_travel_distance: 25755103,
            estimated_travel_duration: 124847,
            image_url: "https://ei.marketwatch.com/Multimedia/2015/03/19/Photos/ZH/MW-DI019_roadtr_20150319151540_ZH.jpg",
            vote_count: 0,
            save_count: 0,
            comments: [],
            created: "2017-01-17",
            updated: "2017-01-17",
        },
        {
            _id: "test04",
            trip_name: "Best Coastal Towns",
            optimized_route: [],
            estimated_travel_distance: 19875030,
            estimated_travel_duration: 823847,
            image_url: "https://vagabond3.com/wp-content/uploads/2011/10/IMG_9478.jpg",
            vote_count: 0,
            save_count: 0,
            comments: [],
            created: "2017-01-17",
            updated: "2017-01-17",
        },
        {
            _id: "test05",
            trip_name: "American Deserts",
            optimized_route: [],
            estimated_travel_distance: 19875030,
            estimated_travel_duration: 198847,
            image_url: "https://images.hgmsites.net/lrg/utah-highway_100231757_l.jpg",
            vote_count: 0,
            save_count: 0,
            comments: [],
            created: "2017-01-17",
            updated: "2017-01-17",
        },
        {
            _id: "test06",
            trip_name: "Prairies",
            optimized_route: [],
            estimated_travel_distance: 19876550,
            estimated_travel_duration: 198238,
            image_url: "https://breathewithus.com/wp-content/uploads/2015/07/iceland-road-trip.jpg",
            vote_count: 0,
            save_count: 0,
            comments: [],
            created: "2017-01-17",
            updated: "2017-01-17",
        },
        {
            _id: "test07",   
            trip_name: "Best Country Roads",
            optimized_route: [],
            estimated_travel_distance: 19875030,
            estimated_travel_duration: 1982287,
            image_url: "http://www.telegraph.co.uk/content/dam/Travel/2017/june/romania-road-trip-AP-TRAVEL-xlarge.jpg",
            vote_count: 0,
            save_count: 0,
            comments: [],
            created: "2017-01-17",
            updated: "2017-01-17",
        },
    ],
    mockWaypointList: [
        "Toronto, ON",
        "Halifax, NS",
        "Boston, MA",
        "New York, NY",
        "Miami, FL",
        "Montreal, QC",
        "Chicago, Il",
        "Winnipeg, MB",
        "Fargo, ND",
        "Calgary, AB",
        "Spokane, WA",
        "Vancouver, BC",
        "Seattle, WA",
        "San Francisco, CA",
        "Los Angeles, CA",
    ],
}